###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: pidhs-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=testword
        - MYSQL_DATABASE=pidhsorg
        - MYSQL_USER=pidhs_user
        - MYSQL_PASSWORD=testword
      ports:
        - "9093:3306"

    webserver:
      image: nginx:alpine
      container_name: pidhs-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9090:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: pidhs-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

